#!/usr/bin/env fish

# Evil Space Quick Reference - Keybinds, Aliases, and Scripts
# Shows a comprehensive reference of commonly used commands with explanations

echo "🗒️  Evil Space Quick Reference" | lolcat --force 2>/dev/null || echo "🗒️  Evil Space Quick Reference"
echo "═══════════════════════════════════════════════════════════════"
echo ""

echo "🔥 HYPRLAND KEYBINDS"
echo "───────────────────"
echo "Super + D         → Launch applications (Evil Launcher)"
echo "Super + W         → Select wallpaper & auto-theme (Evil Launcher)"
echo "Super + Return    → Open terminal (Kitty)"
echo "Super + C         → Close active window"
echo "Super + E         → Open file manager (Nemo)"
echo "Super + V         → Toggle floating window"
echo "Super + F         → Toggle fullscreen"
echo "Super + L         → Lock screen (turn off displays)"
echo "Super + 1-9       → Switch to workspace 1-9"
echo "Super + Shift + 1-9 → Move window to workspace 1-9"
echo "Print             → Screenshot selection"
echo "Shift + Print     → Screenshot full screen"
echo "Super + Print     → Screenshot active window"
echo ""

echo "📁 MEDIA MANAGEMENT"
echo "──────────────────"
echo "organize-media    → Auto-rename files with FileBot (movies, TV, music)"
echo "                    • Detects TV shows vs movies automatically"
echo "                    • Renames to proper format: 'Movie (Year)' or 'Show S01E01'"
echo "                    • Moves to /mnt/Media/Movies or /mnt/Media/TV Shows"
echo "                    • Cleans up junk files and empty folders"
echo ""
echo "vaapi-convert [dir] → Convert .mkv files to H264 with GPU acceleration"
echo "                    • Uses AMD VAAPI for fast GPU encoding"
echo "                    • Reduces file size while maintaining quality"
echo "                    • Skips already converted files"
echo ""

echo "🤖 AI & ANALYSIS TOOLS"
echo "─────────────────────"
echo "log-analyzer live   → Real-time system log monitoring with AI analysis"
echo "                    • Monitors systemd journal for suspicious activity"
echo "                    • AI explanations for critical/high severity events"
echo "                    • Pattern detection for security issues"
echo ""
echo "log-analyzer sudo   → Investigate sudo authentication issues"
echo "log-analyzer security → Security event analysis"
echo "log-analyzer today  → Today's suspicious activity"
echo ""
echo "log-analyzer-tui    → Beautiful TUI interface for log analysis"
echo "                    • Interactive buttons and real-time stats"
echo "                    • Tabbed interface with configuration options"
echo ""
echo "claude-commit       → AI-powered git commit messages"
echo "                    • Analyzes changes and generates conventional commits"
echo "                    • Use --preview to see message without committing"
echo ""

echo "🎨 THEMING & WALLPAPERS"
echo "──────────────────────"
echo "appwall            → Apply wallpaper with Material You theming"
echo "                    • Extracts colors from wallpaper image"
echo "                    • Updates all apps: Waybar, Dunst, GTK, Kitty, etc."
echo "                    • Restarts apps to apply new theme"
echo ""
echo "matugen image <file> → Generate Material You theme from image"
echo "                    • Creates color palette from dominant colors"
echo "                    • Updates all template files automatically"
echo ""

echo "📊 SYSTEM MONITORING"
echo "───────────────────"
echo "dashboard          → Launch Evil Space web dashboard"
echo "                    • Real-time GPU, CPU, memory monitoring"
echo "                    • Log management and analysis"
echo "                    • Theme and wallpaper browser"
echo "                    • Access at http://localhost:8080"
echo ""
echo "htop               → Interactive process viewer"
echo "nvtop              → GPU monitoring (if installed)"
echo "journal logs       → View systemd journal logs"
echo ""

echo "🗂️  FILE & STORAGE"
echo "─────────────────"
echo "media ls           → List media directories and usage"
echo "media space        → Show media storage usage"
echo "media perms        → Check media directory permissions"
echo "media emby         → Show Emby server status"
echo ""
echo "Mount Points:"
echo "  /mnt/Media       → Main media storage (movies, TV, music)"
echo "  /mnt/Stuff       → General storage"
echo ""

echo "🐚 FISH SHELL ABBREVIATIONS"
echo "──────────────────────────"
echo "gs                 → git status"
echo "ga                 → git add"
echo "gaa                → git add --all"
echo "gcm 'message'      → git commit -m 'message'"
echo "gp                 → git push"
echo "gpl                → git pull"
echo "gl                 → git log --oneline --graph --all"
echo "gd                 → git diff"
echo "ll                 → ls -la (detailed list)"
echo "la                 → ls -A (show hidden files)"
echo "..                 → cd .. (go up one directory)"
echo "...                → cd ../.. (go up two directories)"
echo ""

echo "⚙️  DEVELOPMENT TOOLS"
echo "───────────────────"
echo "Scripts Location: ~/dotfiles/scripts/"
echo "  • AI tools:       scripts/ai/"
echo "  • Media tools:    scripts/media/"
echo "  • Setup scripts:  scripts/setup/"
echo "  • Theming:        scripts/theming/"
echo "  • TUI apps:       scripts/tui/"
echo ""
echo "Application Launcher: fuzzel (Super+D)"
echo "Dashboard:         ~/dotfiles/apps/dashboard/"
echo ""

echo "🔧 PACKAGE MANAGEMENT"
echo "────────────────────"
echo "yay -S <package>   → Install package from AUR"
echo "yay -Syu           → Update all packages"
echo "yay -Ss <search>   → Search for packages"
echo "yay -R <package>   → Remove package"
echo "pacman -Qs <search> → Search installed packages"
echo ""

echo "💡 QUICK TIPS"
echo "────────────"
echo "• All theming is done via matugen templates (don't edit CSS directly)"
echo "• Use Super + W to quickly change wallpaper and auto-theme everything"
echo "• organize-media script handles FileBot automation for you"
echo "• dashboard provides web interface for system monitoring"
echo "• log-analyzer provides AI-powered system security monitoring"
echo "• Evil Launcher replaces Fuzzel with better wallpaper integration"
echo ""

echo "📋 FILES & CONFIGS"
echo "─────────────────"
echo "Hyprland config:   ~/.config/hypr/hyprland.conf"
echo "Waybar config:     ~/.config/waybar/"
echo "Fish config:       ~/.config/fish/config.fish"
echo "Dotfiles:          ~/dotfiles/"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "Press any key to close..."
read -n 1 